name: tests

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Cache NPM
        uses: actions/cache@v6
        with:
            path: node_modules
            key: ${{ hashFiles('package-lock.json') }}

      - name: Cache Composer
        uses: actions/cache@v6
        with:
            path: vendor
            key: ${{ hashFiles('composer.lock') }}

      - name: Create db file
        run: touch database/database.sqlite

      - name: Setup PHP
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # v2
        with:
          php-version: '8.5'
          tools: composer:v2
          coverage: none

      - name: Setup Node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: '22'

      - name: Setup Application
        run: composer setup
        if: always()

      - name: Run NPM checks
        run: npm run check
        if: always()

      - name: Run NPM type checks
        run: npm run types:check
        if: always()

      - name: Run Composer Lint
        run: composer lint:check
        if: always()

      - name: Run Composer Type-Check
        run: composer types:check
        if: always()

      - name: Run Artisan Tests
        run: php artisan test --parallel
        if: always()

